### ISSUE TITLE
[Bug]: MO restores in 2 mins+ after dn crash

### ISSUE THREAD

**Issue by dengn** [matrixorigin/matrixone#10034]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-547ae62f
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

A mini MO cluster with 3 * 2c8g, and it doesn't have any user data. 

this is the initial state:
<img width="476" alt="rootGHOST-10-" src="https://github.com/matrixorigin/matrixone/assets/4965857/ad581bce-19df-49c5-ab8f-3ebc1b03ab0a">

I deleted the DN pod intentionally, and watch how long does it take for CN to reconnect. And it takes about 2 min+ to reconnect. As there is no user data at all, this is just too long. 

<img width="528" alt="Every 2 0s kubectl get pod -nmo-hn" src="https://github.com/matrixorigin/matrixone/assets/4965857/17cbf42b-1bad-4828-849f-1eb446d20489">
<img width="827" alt="(20100)： Access denfed for user o 5ot parser error table eoaccount does not exfst" src="https://github.com/matrixorigin/matrixone/assets/4965857/de3664dc-85e5-48e4-8ed9-546cc73bbec2">

**Comment by XuPeng-SH** [comment]
@cnutshell

**Comment by cnutshell** [comment]
no progress yet

**Comment by gouhongshen** [comment]
also see this #8599

**Comment by cnutshell** [comment]
PR #10105 merged, it seems that this issue was resolved. I'll do more check tomorrow.

**Comment by cnutshell** [comment]
I've checked this issue in my local environment via docker-compose.
After dn service restarted, mysql is able to connect to mo-service now.
@dengn PTAL

**Comment by dengn** [comment]
retested in a distributed MO cluster with 7*8c64g, it has no user data but only 3 days of system log. (about 900K statement_info records).

version nightly-7ebfe11d
After deleting DN, it restores the connection in 2min 10seconds. 

Still not as expected.

**Comment by cnutshell** [comment]
Working on another S-1 issue.

**Comment by cnutshell** [comment]
@dengn could you please provide a detailed procedure or document link for how to reproduce this issue?
I'll take this issue ASAP

**Comment by cnutshell** [comment]
I need to reproduce this issue within k8s environment. And I've applied for authority required.

**Comment by cnutshell** [comment]
With commit 7d2dd8c7c, after deleting DN, it restores the connection in 29s.
<img width="715" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/e7da5021-bf4a-4991-8104-39664b2cc561">

**Comment by cnutshell** [comment]
After dn pod deleted, mysql client wouldn't connect to cn service until cn reconnects to dn `logtail-push-service` and makes subscription:

- cn log information when mysql client was success to connect mo-service
<img width="1439" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/9885d267-5dc2-4225-856e-dc3f9a28784c">

- dn log information when dn starts dn `logtail-push-service`
<img width="1427" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/c01f1a4b-418a-481a-9649-2aedb72e63cd">

- dn log information when cn reconnects to dn and makes subscription
<img width="1437" alt="image" src="https://github.com/matrixorigin/matrixone/assets/20291742/b586e113-a0c1-4ea7-8d9b-c56f8e0500a1">

**Comment by cnutshell** [comment]
@dengn PTAL

**Comment by dengn** [comment]
fixed
