### ISSUE TITLE
[Bug]: mo hung after running stability test for about 36 hours on standlone mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#10294]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):f0581e2393473432cd2f0d2c96d6749462da06b0
- Hardware parameters:16C 64G
- OS type:
- Others:
```

### Actual Behavior

after running stability test for about 36 hours on standlone mode, the mo was hung and can not connected agian.
<img width="945" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/e23dca10-cd20-449b-a42c-40d864782d32">

mo log:
[hung.log.tar.gz](https://github.com/matrixorigin/matrixone/files/11901421/hung.log.tar.gz)

prfoile(cpu,heap, goroutine,trace)
[hung-profile.tar.gz](https://github.com/matrixorigin/matrixone/files/11901390/hung-profile.tar.gz)

### Steps to Reproduce

```Markdown
run a mo tester on stanlone and run the following test
1. bvt loop
   git clone mo-tester
   ./run.sh -n -g -p  xxxxx/matrixone/test/distributed/cases -e ddl -t 100

2. tpch loop 
   git clone mo-tpch, laod tpch 10G data
   ./run.sh -q all -s 10 -t 50000

3. sysbench mixed
   git clone mo-load, and init 10-talbes-100000-per-table 
   ./start.sh -m SYSBENCH -n 10 -s 100000
   ./start.sh -c cases/sysbench/mixed_10_100000/ -d 5000 -g

4. tpcc 10-10 long run
   git clone mo-tpcc, and load tpcc 10 warehouse data, and modify runMins to 5000 in props.mo
   ./runBenchmark.sh props.mo
```

**Comment by daviszhen** [comment]
分析了trace文件，有些发现。

登录时，要开启新事务，取时间戳卡住。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/696cd46b-856a-496a-b5d2-df9ffc3f0c6d)

**Comment by daviszhen** [comment]
另外两个卡住的routine 类似。

![image](https://github.com/matrixorigin/matrixone/assets/60595215/69680931-9aa7-4bef-b7f5-b0f8bad68e62)

![image](https://github.com/matrixorigin/matrixone/assets/60595215/3370c6cc-286b-48eb-b25e-444bf4c5686e)

**Comment by volgariver6** [comment]
fixed by @m-schen

**Comment by m-schen** [comment]
我改的是重连过程中的一个死锁。

触发重连的原因是logservice在commit的时候有一个append commit什么的花了10+分钟 @volgariver6

**Comment by m-schen** [comment]
@aressu1985 
我修复了重连发生死锁导致的hung住。不过触发重连的原因是commit时间很长，导致期间cn与dn这段时间都没有logtail，这个问题我没有修复。我issue转回去了，看就这个commit append过长是要重新开一个issue跟踪还是已有issue在跟踪了，或者就这个issue让负责的人跟踪该问题，你来决定哈。

**Comment by m-schen** [comment]
<img width="935" alt="image" src="https://github.com/matrixorigin/matrixone/assets/59043531/12bfbe3a-0fb9-4fb3-94c9-b2532ca6dea2">
it takes too much time here. line 575555

**Comment by aressu1985** [comment]
This issue has still exists for commit: d19e2b0a2b35d217c64d72e7bd1d07a00890b55a

**Comment by fengttt** [comment]
This maybe the same as #9867 or #9883 

@volgariver6 do you agree?

**Comment by volgariver6** [comment]
> This maybe the same as #9867 or #9883
> 
> @volgariver6 do you agree?

Yes, they are all the same.

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
最近standalone测试都没有复现，先降级s0，一边观察一边分析

**Comment by volgariver6** [comment]
dup with #9883

**Comment by aressu1985** [comment]
this closed and tracked by #9883
