### ISSUE TITLE
[Bug]: LOAD TPCH 10G DATA and BATCH INSERT ERROR by context deadline exceeded

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#6312]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):92439b1d3f73552ca912de6180099821c39955fd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

chbechmark batch insert data :
2022-11-06 00:49:29 ERROR Loader:335 - context deadline exceeded
2022-11-06 00:49:29 ERROR Loader:336 - s_w_id = 1, s_i_id = 91000

Loading data/10/orders.tbl in to table orders,please wait.....
load data infile '/data1/sudong/mo-regression/tools/mo-tpch/data/10/orders.tbl' into table tpch_10g.orders FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
mysql: [Warning] Using a password on the command line interface can be insecure.

because of the logs is very large, I dont find the right errror message, if want to reproduce ,contract me

**Comment by zhangxu19830126** [comment]
change rpc max message size to 1GB, deadline error resovled. But query is blocked. @JasonPeng1310 please take a look

**Comment by aressu1985** [comment]
[server (1).log](https://github.com/matrixorigin/matrixone/files/9945959/server.1.log)

**Comment by aressu1985** [comment]
fixed: e23e00f1d01d43e33c509a6d239ccc38b5f93409

**Comment by LeftHandCold** [comment]
The batch insert of cn-dn is nearly twice as slow as the stand-alone version, and is mainly consumed in the checkPrimaryKey of cn.
![image](https://user-images.githubusercontent.com/14086886/200351308-3472dae9-399f-42ef-8c72-9d0e9b3afb7a.png)

**Comment by fengttt** [comment]
Closed too soon -- @jianwan0214 please complete a tpch10g load and attach profiling data here.

**Comment by fengttt** [comment]
Bug fixed.   Perf issue remains, as show in profiling.    Downgrade to S0.

To address perf issue:
1. CN to enable dedup up to snapshot.   We expect this further slow down load.
2. DN to enable dedup from a snapshot.   This should reduce DN workload and reduce load time somewhat.
3. CN to enable direct S3 write mode, and DN must impl dedup from a snapshot with S3.   In common case, DN cost should be 0.
4. After 3, we expect load back to at least the same as standalone.   
5. CN does not need to break load into separate transactions.
6. Further optimization (load and verify, or totally skip verify).

**Comment by reusee** [comment]
will continue on this one after the tree opens for 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
will be in 0.7

**Comment by reusee** [comment]
will do this in 0.7

**Comment by reusee** [comment]
will do this in 0.7

**Comment by reusee** [comment]
in progress

**Comment by reusee** [comment]
This issue could be closed, the remaining work is being tracked at https://github.com/matrixorigin/matrixone/issues/6949

**Comment by reusee** [comment]
@aressu1985 Please close this since it's being tracked in #6949

**Comment by reusee** [comment]
Re-assign back to @aressu1985
