### ISSUE TITLE
[Bug]: expired transaction appeared in multi-cns scenario

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#6317]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):92439b1d3f73552ca912de6180099821c39955fd
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

many errors occurred in cn-1 when multi-cn started.

CN1: following error log repeated forever, and cn1 cannot work properly
```
{"level":"ERROR","time":"2022/11/06 07:13:27.596872 +0000","caller":"frontend/util.go:493","msg":"query trace status","connection_id":1001,"statement":"select task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, task_parent_id, task_status, task_runner, task_epoch, last_heartbeat, result_code, error_msg, create_at, end_at from mo_task.sys_async_task where task_id > 0 and task_runner = \"00000000-0000-0000-0000-200000000001\" order by task_id limit 1","status":"fail","error":"the transaction has been committed or aborted","session_info":"connectionId 1001","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:477\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:469\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3031\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3100\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:159"}


{"level":"INFO","time":"2022/11/06 07:13:37.598107 +0000","caller":"frontend/util.go:483","msg":"query trace","connection_id":1001,"query":"use mo_task","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:13:37.600388 +0000","caller":"frontend/util.go:498","msg":"User f3748a89-40c0-4489-885e-86370948be6e change database from [mo_task] to [mo_task] connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:13:37.600472 +0000","caller":"frontend/util.go:483","msg":"query trace status","connection_id":1001,"statement":"use mo_task","status":"success","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:13:37.600575 +0000","caller":"frontend/util.go:483","msg":"query trace","connection_id":1001,"query":"select \n    \t\t\t\t\t\ttask_id,\n\t\t\t\t\t\t\ttask_metadata_id,\n\t\t\t\t\t\t\ttask_metadata_executor,\n\t\t\t\t\t\t\ttask_metadata_context,\n\t\t\t\t\t\t\ttask_metadata_option,\n\t\t\t\t\t\t\ttask_parent_id,\n\t\t\t\t\t\t\ttask_status,\n\t\t\t\t\t\t\ttask_runner,\n\t\t\t\t\t\t\ttask_epoch,\n\t\t\t\t\t\t\tlast_heartbeat,\n\t\t\t\t\t\t\tresult_code,\n\t\t\t\t\t\t\terror_msg,\n\t\t\t\t\t\t\tcreate_at,\n\t\t\t\t\t\t\tend_at \n\t\t\t\t\t\tfrom mo_task.sys_async_task where task_id>0 AND task_runner='00000000-0000-0000-0000-200000000001' order by task_id limit 1","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:13:37.685884 +0000","caller":"frontend/util.go:498","msg":"time of Exec.Build : 85.172796ms connectionId 1001"}
{"level":"ERROR","time":"2022/11/06 07:13:37.686910 +0000","caller":"frontend/util.go:493","msg":"the transaction has been committed or aborted","session_info":"connectionId 1001","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3023\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3100\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:159"}
{"level":"ERROR","time":"2022/11/06 07:13:37.687010 +0000","caller":"frontend/util.go:493","msg":"query trace status","connection_id":1001,"statement":"select task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, task_parent_id, task_status, task_runner, task_epoch, last_heartbeat, result_code, error_msg, create_at, end_at from mo_task.sys_async_task where task_id > 0 and task_runner = \"00000000-0000-0000-0000-200000000001\" order by task_id limit 1","status":"fail","error":"the transaction has been committed or aborted","session_info":"connectionId 1001","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:477\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:469\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3031\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3100\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:159"}
```

I tried to access cn1 locally, I get `access denied` error in client side, and error log in server side is as following:

```
{"level":"INFO","time":"2022/11/06 07:27:43.882137 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:43.965548 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:45.582772 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:45.861632 +0000","caller":"frontend/util.go:483","msg":"query trace","connection_id":1001,"query":"use mo_task","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:45.864223 +0000","caller":"frontend/util.go:498","msg":"User f3748a89-40c0-4489-885e-86370948be6e change database from [mo_task] to [mo_task] connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:45.864524 +0000","caller":"frontend/util.go:483","msg":"query trace status","connection_id":1001,"statement":"use mo_task","status":"success","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:45.864580 +0000","caller":"frontend/util.go:483","msg":"query trace","connection_id":1001,"query":"select \n    \t\t\t\t\t\ttask_id,\n\t\t\t\t\t\t\ttask_metadata_id,\n\t\t\t\t\t\t\ttask_metadata_executor,\n\t\t\t\t\t\t\ttask_metadata_context,\n\t\t\t\t\t\t\ttask_metadata_option,\n\t\t\t\t\t\t\ttask_parent_id,\n\t\t\t\t\t\t\ttask_status,\n\t\t\t\t\t\t\ttask_runner,\n\t\t\t\t\t\t\ttask_epoch,\n\t\t\t\t\t\t\tlast_heartbeat,\n\t\t\t\t\t\t\tresult_code,\n\t\t\t\t\t\t\terror_msg,\n\t\t\t\t\t\t\tcreate_at,\n\t\t\t\t\t\t\tend_at \n\t\t\t\t\t\tfrom mo_task.sys_async_task where task_id>0 AND task_runner='00000000-0000-0000-0000-200000000001' order by task_id limit 1","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:45.937086 +0000","caller":"frontend/util.go:498","msg":"time of Exec.Build : 72.320677ms connectionId 1001"}
{"level":"ERROR","time":"2022/11/06 07:27:45.938191 +0000","caller":"frontend/util.go:493","msg":"the transaction has been committed or aborted","session_info":"connectionId 1001","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3023\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3100\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:159"}
{"level":"ERROR","time":"2022/11/06 07:27:45.938545 +0000","caller":"frontend/util.go:493","msg":"query trace status","connection_id":1001,"statement":"select task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, task_parent_id, task_status, task_runner, task_epoch, last_heartbeat, result_code, error_msg, create_at, end_at from mo_task.sys_async_task where task_id > 0 and task_runner = \"00000000-0000-0000-0000-200000000001\" order by task_id limit 1","status":"fail","error":"the transaction has been committed or aborted","session_info":"connectionId 1001","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:477\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:469\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3031\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3100\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:159"}
{"level":"INFO","time":"2022/11/06 07:27:46.902301 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:46.981400 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:48.664122 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:49.882796 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:49.964533 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:50.374765 +0000","caller":"frontend/util.go:498","msg":"time of Exec.Build : 74.833343ms "}
{"level":"ERROR","time":"2022/11/06 07:27:50.375652 +0000","caller":"frontend/util.go:493","msg":"the transaction has been committed or aborted","session_info":"","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3023\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*BackgroundHandler).Exec\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1863\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeSQLInBackgroundSession\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1817\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Session).AuthenticateUser\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1048\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).authenticateUser\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_protocol.go:1078\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).handleHandshake\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_protocol.go:1177\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:254\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:344"}
{"level":"ERROR","time":"2022/11/06 07:27:50.375771 +0000","caller":"frontend/util.go:493","msg":"query trace status","connection_id":4294967295,"statement":"select account_id, account_name from mo_catalog.mo_account where account_name = \"sys\"","status":"fail","error":"the transaction has been committed or aborted","session_info":"","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:477\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:469\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3031\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*BackgroundHandler).Exec\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1863\ngithub.com/matrixorigin/matrixone/pkg/frontend.executeSQLInBackgroundSession\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1817\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Session).AuthenticateUser\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1048\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).authenticateUser\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_protocol.go:1078\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).handleHandshake\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_protocol.go:1177\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:254\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:344"}
{"level":"ERROR","time":"2022/11/06 07:27:50.375931 +0000","caller":"frontend/mysql_protocol.go:1178","msg":"authenticate user failed.error:the transaction has been committed or aborted","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlProtocolImpl).handleHandshake\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_protocol.go:1178\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:254\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:344"}
{"level":"ERROR","time":"2022/11/06 07:27:50.376006 +0000","caller":"frontend/util.go:508","msg":"error:the transaction has been committed or aborted connectionId 1003","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logErrorf\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:508\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine_manager.go:256\ngithub.com/fagongzi/goetty/v2.(*server).doConnection\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:381\ngithub.com/fagongzi/goetty/v2.(*server).doStart.func2.1\n\t/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:344"}
{"level":"ERROR","time":"2022/11/06 07:27:50.376045 +0000","caller":"v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:383","msg":"session handle failed, close this session","listen-addresses":"[0.0.0.0:6001]","session-id":3,"addr":"127.0.0.1:45636","error":"the transaction has been committed or aborted"}
{"level":"ERROR","time":"2022/11/06 07:27:50.376060 +0000","caller":"v2@v2.0.3-0.20221103025002-a4c7a0d38815/application.go:345","msg":"handle session failed","listen-addresses":"[0.0.0.0:6001]","error":"the transaction has been committed or aborted"}
{"level":"INFO","time":"2022/11/06 07:27:51.740186 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:52.894028 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:53.013405 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:54.827065 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:55.889393 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:55.939541 +0000","caller":"frontend/util.go:483","msg":"query trace","connection_id":1001,"query":"use mo_task","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:55.942799 +0000","caller":"frontend/util.go:498","msg":"User f3748a89-40c0-4489-885e-86370948be6e change database from [mo_task] to [mo_task] connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:55.942891 +0000","caller":"frontend/util.go:483","msg":"query trace status","connection_id":1001,"statement":"use mo_task","status":"success","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:55.943086 +0000","caller":"frontend/util.go:483","msg":"query trace","connection_id":1001,"query":"select \n    \t\t\t\t\t\ttask_id,\n\t\t\t\t\t\t\ttask_metadata_id,\n\t\t\t\t\t\t\ttask_metadata_executor,\n\t\t\t\t\t\t\ttask_metadata_context,\n\t\t\t\t\t\t\ttask_metadata_option,\n\t\t\t\t\t\t\ttask_parent_id,\n\t\t\t\t\t\t\ttask_status,\n\t\t\t\t\t\t\ttask_runner,\n\t\t\t\t\t\t\ttask_epoch,\n\t\t\t\t\t\t\tlast_heartbeat,\n\t\t\t\t\t\t\tresult_code,\n\t\t\t\t\t\t\terror_msg,\n\t\t\t\t\t\t\tcreate_at,\n\t\t\t\t\t\t\tend_at \n\t\t\t\t\t\tfrom mo_task.sys_async_task where task_id>0 AND task_runner='00000000-0000-0000-0000-200000000001' order by task_id limit 1","session_info":"connectionId 1001"}
{"level":"INFO","time":"2022/11/06 07:27:55.974497 +0000","caller":"disttae/engine.go:95","msg":"error: the transaction has been committed or aborted","span":{}}
{"level":"INFO","time":"2022/11/06 07:27:56.017524 +0000","caller":"frontend/util.go:498","msg":"time of Exec.Build : 74.219678ms connectionId 1001"}
{"level":"ERROR","time":"2022/11/06 07:27:56.018640 +0000","caller":"frontend/util.go:493","msg":"the transaction has been committed or aborted","session_info":"connectionId 1001","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3023\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3100\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:159"}
{"level":"ERROR","time":"2022/11/06 07:27:56.018731 +0000","caller":"frontend/util.go:493","msg":"query trace status","connection_id":1001,"statement":"select task_id, task_metadata_id, task_metadata_executor, task_metadata_context, task_metadata_option, task_parent_id, task_status, task_runner, task_epoch, last_heartbeat, result_code, error_msg, create_at, end_at from mo_task.sys_async_task where task_id > 0 and task_runner = \"00000000-0000-0000-0000-200000000001\" order by task_id limit 1","status":"fail","error":"the transaction has been committed or aborted","session_info":"connectionId 1001","stacktrace":"github.com/matrixorigin/matrixone/pkg/frontend.logError\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:493\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStringStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:477\ngithub.com/matrixorigin/matrixone/pkg/frontend.logStatementStatus\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/util.go:469\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3031\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:3100\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/routine.go:159"}
```

### Steps to Reproduce

1. start a cluster with two CNs(If you want to start a mo cluster in eks, you can following this guideline document: https://github.com/matrixorigin/docs/blob/main/dev/guide/MO%20Operator%20%E7%9A%84%E4%BD%BF%E7%94%A8%E4%B8%8E%E6%B5%8B%E8%AF%95%EF%BC%88%E5%86%85%E9%83%A8%E7%89%88%E6%9C%AC%EF%BC%89.md)
2. execute drop table if exist create table xxx repeatedly

Configuration of each node is here:
[Archive.zip](https://github.com/matrixorigin/matrixone/files/9946010/Archive.zip)

```


### Additional information

_No response_

**Comment by nnsgmsone** [comment]
https://github.com/matrixorigin/matrixone/pull/6351

**Comment by nnsgmsone** [comment]
Pass the correct contextual information when running across nodes

**Comment by nnsgmsone** [comment]
It should be fixed by #6408. Please ask Peng Zheng to help to cross-check again.

**Comment by fengttt** [comment]
@daviszhen Can you please leave a note why you unassigned yourself?    Verified?

**Comment by mooleetzi** [comment]
configuring env to see if repro after last related pr merged

**Comment by mooleetzi** [comment]
imagesId:nightly-d09d0760.
2 cn, 1 dn 3 log in s3.
tried [table.txt](https://github.com/matrixorigin/matrixone/files/9978688/table.txt) on cn-0.
there is still some error: 
`context canceled`,`context deadline exceeded` in cn-0.log.

After executing table.txt(table.sql), cn-0 will lost connection in a short while(10s), then  both cn-0 and cn-1 cannot connect .

Some rpc error in cn-1 while I try to connect cn-1 after cn0 lost connection.
<img width="970" alt="截屏2022-11-10 16 48 52" src="https://user-images.githubusercontent.com/42628885/201043915-1dd13651-5662-4d07-9e91-5f9b80ad8986.png">


[cn-1.log](https://github.com/matrixorigin/matrixone/files/9978979/cn-1.log)

**Comment by mooleetzi** [comment]
`the transaction has been committed or aborted` still exists
```
 {"level":"ERROR","time":"2022/11/10 07:38:55.285417 +0000","caller":"client/operator.go:390","msg       ":"error: the transaction has been committed or aborted","stacktrace":"github.com/matrixorigin/ma       trixone/pkg/txn/client.(*txnOperator).checkStatus\n\t/go/src/github.com/matrixorigin/matrixone/pk       g/txn/client/operator.go:390\ngithub.com/matrixorigin/matrixone/pkg/txn/client.(*txnOperator).val       idate\n\t/go/src/github.com/matrixorigin/matrixone/pkg/txn/client/operator.go:380\ngithub.com/mat       rixorigin/matrixone/pkg/txn/client.(*txnOperator).Read\n\t/go/src/github.com/matrixorigin/matrixo       ne/pkg/txn/client/operator.go:236\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/disttae.getLog       Tail\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/logtail.go:57\ngithub.com       /matrixorigin/matrixone/pkg/vm/engine/disttae.updatePartition\n\t/go/src/github.com/matrixorigin/       matrixone/pkg/vm/engine/disttae/logtail.go:41\ngithub.com/matrixorigin/matrixone/pkg/vm/engine/di       sttae.(*DB).Update\n\t/go/src/github.com/matrixorigin/matrixone/pkg/vm/engine/disttae/db.go:285\n       github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).New\n\t/go/src/github.com/matri       xorigin/matrixone/pkg/vm/engine/disttae/engine.go:254\ngithub.com/matrixorigin/matrixone/pkg/fron       tend.(*TxnHandler).NewTxn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:12       65\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Session).TxnStart\n\t/go/src/github.com/matr       ixorigin/matrixone/pkg/frontend/session.go:856\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*       TxnHandler).GetTxn\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/session.go:1406\ngit       hub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).handleChangeDB\n\t/go/src/github.       com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.go:970\ngithub.com/matrixorigin/matrix       one/pkg/frontend.(*MysqlCmdExecutor).doComQuery\n\t/go/src/github.com/matrixorigin/matrixone/pkg/       frontend/mysql_cmd_executor.go:2540\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExe       cutor).ExecRequest\n\t/go/src/github.com/matrixorigin/matrixone/pkg/frontend/mysql_cmd_executor.g       o:3125\ngithub.com/matrixorigin/matrixone/pkg/frontend.(*Routine).Loop\n\t/go/src/github.com/matr       ixorigin/matrixone/pkg/frontend/routine.go:159"}

```

**Comment by mooleetzi** [comment]
no progress, waiting for https://github.com/matrixorigin/matrixone/pull/6450

**Comment by mooleetzi** [comment]
imageId: [nightly-297949c4](https://hub.docker.com/layers/matrixorigin/matrixone/nightly-297949c4/images/sha256-02c290cdd31ec7b5edfdec95fb3864795bc21d76572436c04f5187981644d6ea?context=explore)
2 cn, 1 dn 3 log in s3.
tried [testSql](https://github.com/matrixorigin/matrixone/files/9978688/table.txt) on cn-1.

all test sql query ok and no `the transaction has been committed or aborted` exists.
<img width="974" alt="截屏2022-11-12 15 16 03" src="https://user-images.githubusercontent.com/42628885/201462416-1f7c05d1-f1c9-4353-bf87-5630d19dd0d6.png">

<img width="822" alt="截屏2022-11-12 15 25 02" src="https://user-images.githubusercontent.com/42628885/201462723-cecca1af-e3e6-4aef-b13d-ff954dadd082.png">

seems fixed.

**Comment by sukki37** [comment]
Verified on the last few versions, there is no longer a repro
