### ISSUE TITLE
[Bug]: Colmun name in a view is always lowercase even if it is defined as case sensitive using ``

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#8359]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):21cffccc42250fb2987349c5ab381b4916e337f3
- Hardware parameters:16c 64g
- OS type:
cat /etc/centos-release
CentOS Stream release 8
uname -r
6.0.10-1.el8.elrepo.x86_64
- Others:
```

### Actual Behavior

Colmun name in a view is always lowercase even if it is defined as case sensitive using ``
```
mysql> create table TAB_1 (`COLA` int);
Query OK, 0 rows affected (0.01 sec)

mysql> 
mysql> 
mysql> create view VIEW_1 as Select `COLA` AS `COLA` from TAB_1;
Query OK, 0 rows affected (0.01 sec)

mysql> select `COLA` from TAB_1;
Empty set (0.00 sec)

mysql> select `COLA` from VIEW_1;
ERROR 20301 (HY000): invalid input: column COLA does not exist
mysql> 
mysql> select COLA from VIEW_1;
Empty set (0.01 sec)

mysql> select colA from VIEW_1;
Empty set (0.00 sec)

mysql> select `cola` from VIEW_1;
Empty set (0.01 sec)

mysql> select `colA` from VIEW_1;
ERROR 20301 (HY000): invalid input: column colA does not exist
```

### Expected Behavior

The column name should be case sensitive if it is defined using ``. In the above case, these sql should work.
```
select `COLA` from VIEW_1;
select COLA from VIEW_1;
select COLa from VIEW_1;
select CoLA from VIEW_1;
```

### Steps to Reproduce

```Markdown
create table TAB_1 (`COLA` int);
create view VIEW_1 as Select `COLA` AS `COLA` from TAB_1;
create view VIEW_1 as Select `COLA` AS `COLA` from TAB_1;
select `COLA` from TAB_1;
select `COLA` from VIEW_1;
select COLA from VIEW_1;
select colA from VIEW_1;
```
```


### Additional information

none

**Comment by iamlinjunhong** [comment]
fixed in 6880d4f6e52ed388648e41f8e6a5e3b0d692cad8

**Comment by aronchanisme** [comment]
upgraded mo to 52c4be26cad6879979b12d711937a41984113429
Now it looks like the column name is not case sensitive no matter what, even if the column is defined using ``.
```
mysql> create table TAB_1 (`COLA` int);
Query OK, 0 rows affected (0.01 sec)

mysql> 
mysql> create view VIEW_1 as Select `COLA` AS `COLA` from TAB_1;
ERROR 1050 (HY000): table view_1 already exists
mysql> 
mysql> drop view VIEW_1;
Query OK, 0 rows affected (0.01 sec)

mysql> create view VIEW_1 as Select `COLA` AS `COLA` from TAB_1;
Query OK, 0 rows affected (0.01 sec)

mysql> select `COLA` from TAB_1;
Empty set (0.01 sec)

mysql> 
mysql> select `COLA` from VIEW_1;
Empty set (0.00 sec)

mysql> 
mysql> select COLA from VIEW_1;
Empty set (0.01 sec)

mysql> select `cola` from VIEW_1;
Empty set (0.00 sec)

mysql> select `colA` from VIEW_1;
Empty set (0.00 sec)

mysql> select `colA` from tab_1;
Empty set (0.00 sec)
```

**Comment by aronchanisme** [comment]
commit id: 16acd36f0eb2d764d6c86dd7ff87ceba7167f666

As per discussed with @m-schen, a configuration parameter is implemented to control whether table name is case sensitive or not, in `./etc/launch-tae-CN-tae-DN/cn.toml`,
 ```
[cn.frontend]
lower_case_tables_name = 0 # default as 1, meaning case is not sensitive 
```

However I've set this value to 0, but I am still getting this result,
```
mysql> use case_test;
Database changed
mysql> create table t1 (`COLA` int);
Query OK, 0 rows affected (0.01 sec)

mysql> select `COLA` from t1;
Empty set (0.01 sec)

mysql> select `cola` from t1;
Empty set (0.00 sec)
```

Looks like it is not acting as what I expected.

**Comment by aronchanisme** [comment]
It seems the conf parameter is working with column names in tables, but not working with column names in views. @iamlinjunhong  Is this normal?

commitid:
```bash
commit bc581a4cc2b3e0876ab2bdf8f09e0d77059c7994 (HEAD -> main, origin/main, origin/HEAD)
Author: zengyan1 <93656539+zengyan1@users.noreply.github.com>
Date:   Sat May 6 15:36:30 2023 +0800
```

conf:
```bash
# etc/launch-tae-CN-tae-DN/cn.toml
# ...
[cn.frontend]
lowerCaseTableNames = "0"
```

test result:
```bash
mysql> create table t1 (`COLA` int);
Query OK, 0 rows affected (0.01 sec)

mysql> select `COLA` from t1;
Empty set (0.01 sec)

mysql> select `cola` from t1;
ERROR 20301 (HY000): invalid input: column cola does not exist

mysql> create view v1 as Select `COLA` AS `COLA` from t1;
Query OK, 0 rows affected (0.02 sec)

mysql> select `COLA` from v1;
ERROR 20301 (HY000): invalid input: column cola does not exist

mysql> select COLA from v1;
ERROR 20301 (HY000): invalid input: column cola does not exist

mysql> desc v1;
+-------+---------+------+------+---------+-------+---------+
| Field | Type    | Null | Key  | Default | Extra | Comment |
+-------+---------+------+------+---------+-------+---------+
| cola  | INT(32) | YES  |      | NULL    |       |         |
+-------+---------+------+------+---------+-------+---------+
1 row in set (0.01 sec)

mysql> select cola from v1;
ERROR 20301 (HY000): invalid input: column cola does not exist

mysql> select `cola` from v1;
ERROR 20301 (HY000): invalid input: column cola does not exist

mysql> select * from v1;
ERROR 20301 (HY000): invalid input: column cola does not exist

mysql> desc t1;
+-------+---------+------+------+---------+-------+---------+
| Field | Type    | Null | Key  | Default | Extra | Comment |
+-------+---------+------+------+---------+-------+---------+
| COLA  | INT(32) | YES  |      | NULL    |       |         |
+-------+---------+------+------+---------+-------+---------+
1 row in set (0.01 sec)

mysql> select `COLA` from t1;
Empty set (0.00 sec)

mysql> select `COLA` from v1;
ERROR 20301 (HY000): invalid input: column cola does not exist
mysql> 
```

**Comment by aronchanisme** [comment]
as per discussed, pls kindly help take a look @daviszhen
